
# tap repositories and their packages

tap bonty/omnisharpserver

tap caskroom/cask
brew brew-cask
cask 0xed
cask 1password
cask adobe-air
cask adobe-creative-cloud
cask adobe-reader
cask alfred
cask amethyst
cask android-studio
cask appcleaner
cask atom
cask bettertouchtool
cask blender
cask box-sync
cask charles
cask chefdk
cask coteditor
cask crashlytics
cask dropbox
cask firefox
cask flash
cask flip4mac
cask genymotion
cask google-chrome
cask google-cloud-sdk
cask google-japanese-ime
cask heroku-toolbelt
cask honer
cask istat-menus
cask iterm2
cask java
cask karabiner
cask kindle
cask league-of-legends
cask libreoffice
cask mono-mdk
cask seil
cask sequel-pro
cask skype
cask sourcetree
cask spotify
cask steam
cask td-agent
cask texturepacker
cask unity
cask vagrant
cask virtualbox
cask vlc
cask wireshark
cask xamarin-studio
cask xquartz

tap homebrew/binary
brew jad

tap homebrew/brewdler

tap macoshita/custom
brew tmux-patched

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty

# Other Homebrew packages
brew android-ndk
brew android-sdk
brew ant
brew apktool
brew autoconf
brew automake
brew aws-elasticache
brew binutils
brew bison
brew bitlbee
brew boost
brew cairo
brew cask
brew clib
brew cmake
brew cmigemo
brew coreutils
brew csshx
brew czmq
brew dex2jar
brew dnsmasq
brew docker
brew docker-compose
brew docker-machine
brew docker-swarm
brew ec2-api-tools
brew emacs --with-cocoa --with-gnutls
brew fdupes
brew findutils
brew fontconfig
brew fontforge
brew freetype
brew gdbm
brew gettext
brew gibo
brew git
brew git-flow
brew glib
brew gmp
brew gnu-sed
brew gnutls
brew gobject-introspection
brew gradle
brew harfbuzz
brew hub
brew icu4c
brew imagemagick
brew jpeg
brew jq
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libpng
brew libsodium
brew libtasn1
brew libtiff
brew libtool
brew libyaml
brew llvm
brew lnav
brew lv
brew mackup
brew memcached
brew mercurial
brew mobile-shell
brew mono
brew mysql
brew nettle
brew nkf
brew node
brew omnisharp-server
brew oniguruma
brew openssl
brew pango
brew pcre
brew perl-build
brew pixman
brew pkg-config
brew plenv
brew postgresql
brew protobuf
brew pyenv
brew rbenv
brew rbenv-gemset
brew readline
brew reattach-to-user-namespace
brew redis
brew rmtrash
brew ruby-build
brew source-highlight
brew sqlcipher
brew terraform
brew texinfo
brew tig
brew tree
brew weechat --with-ruby --with-python --with-perl --with-ruby --with-python --with-perl
brew wget
brew xcproj
brew xctool
brew xz
brew z
brew zeromq
brew zsh --without-etcdir

# App Store applications
appstore Clear
appstore Dash
appstore Deckset
appstore GarageBand
appstore Growl
appstore Gyazo
appstore iMovie
appstore Keynote
appstore Kobito
appstore LINE
appstore Numbers
appstore Pages
appstore Pixelmator
appstore PopClip
appstore Slack
appstore The Unarchiver
appstore Transmit
appstore Twitter
appstore Xcode
